package com.wangqi.entity;
// Generated 2018-11-5 19:53:55 by Hibernate Tools 4.3.5.Final

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private Integer id;
	private Department department;
	private String name;

	public Employee() {
	}

	public Employee(String name) {
		super();
		this.name = name;
	}

	public Employee(Department department) {
		this.department = department;
	}

	public Employee(Department department, String name) {
		this.department = department;
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
