package com.wangqi.entity;
// Generated 2018-11-6 14:07:20 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private Integer sid;
	private String sname;
	private String saddress;
	private String grade;
	private Set<Teacher> teachers = new HashSet<Teacher>();

	public Student() {
	}


	public Student(Integer sid, String sname, String saddress, String grade, Set<Teacher> teachers) {
		super();
		this.sid = sid;
		this.sname = sname;
		this.saddress = saddress;
		this.grade = grade;
		this.teachers = teachers;
	}


	public Student(String sname, String saddress, String grade) {
		super();
		this.sname = sname;
		this.saddress = saddress;
		this.grade = grade;
	}


	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public String getSaddress() {
		return this.saddress;
	}

	public void setSaddress(String saddress) {
		this.saddress = saddress;
	}

	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}


	public Set<Teacher> getTeachers() {
		return teachers;
	}


	public void setTeachers(Set<Teacher> teachers) {
		this.teachers = teachers;
	}


	@Override
	public String toString() {
		return "Student [sid=" + sid + ", sname=" + sname + ", saddress=" + saddress + ", grade=" + grade
				+ ", teachers=" + teachers + "]";
	}


}
