package com.wangqi.entity;
// Generated 2018-11-6 14:07:20 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Teacher generated by hbm2java
 */
public class Teacher implements java.io.Serializable {

	private Integer tid;
	private String tname;
	private Integer age;
	private String course;
	private Set<Student> studentTeachers = new HashSet<Student>();

	public Teacher() {
	}

	public Teacher(Integer tid, String tname, Integer age, String course, Set<Student> studentTeachers) {
		super();
		this.tid = tid;
		this.tname = tname;
		this.age = age;
		this.course = course;
		this.studentTeachers = studentTeachers;
	}


	public Teacher(String tname, Integer age, String course) {
		super();
		this.tname = tname;
		this.age = age;
		this.course = course;
	}

	public Integer getTid() {
		return this.tid;
	}

	public void setTid(Integer tid) {
		this.tid = tid;
	}

	public String getTname() {
		return this.tname;
	}

	public void setTname(String tname) {
		this.tname = tname;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getCourse() {
		return this.course;
	}

	public void setCourse(String course) {
		this.course = course;
	}

	public Set<Student> getStudentTeachers() {
		return studentTeachers;
	}

	public void setStudentTeachers(Set<Student> studentTeachers) {
		this.studentTeachers = studentTeachers;
	}

	@Override
	public String toString() {
		return "Teacher [tid=" + tid + ", tname=" + tname + ", age=" + age + ", course=" + course + "]";
	}



}
